// Generated by scripts/generate-changelog.mjs. Do not edit by hand.
import type { AppChangelog } from "../src/types";

export const APP_CHANGELOG = {
  "generatedAt": "2026-06-30T14:58:56+02:00",
  "repositoryUrl": "https://github.com/BasPeter/data-vault.git",
  "releases": [
    {
      "version": "0.12.6",
      "date": "2026-06-30T14:58:56+02:00",
      "commits": [
        {
          "hash": "5585ea8490f99a6ce83733ff74876c3d32acc051",
          "shortHash": "5585ea8",
          "subject": "Clarify vault commit prompt repository"
        }
      ]
    },
    {
      "version": "0.12.5",
      "date": "2026-06-30T14:38:09+02:00",
      "commits": [
        {
          "hash": "b43eac513726778fca17b385a27b43a37999a15f",
          "shortHash": "b43eac5",
          "subject": "Prepare release 0.12.5"
        },
        {
          "hash": "86d73443d75a8dc3f5724abb3f90aacf6a3d8f99",
          "shortHash": "86d7344",
          "subject": "Add vault document change indicator"
        }
      ]
    },
    {
      "version": "0.12.4",
      "date": "2026-06-30T14:12:01+02:00",
      "commits": [
        {
          "hash": "b8204d13cc910a52fc625594e9dd2d04f275b060",
          "shortHash": "b8204d1",
          "subject": "Fix workspace e2e skill version"
        },
        {
          "hash": "8d509f1fb75a8e404a19299f969dd694b13c080a",
          "shortHash": "8d509f1",
          "subject": "Prepare release 0.12.4"
        },
        {
          "hash": "af48a3c6a2134e92eb4d9a016ac25a045266b37b",
          "shortHash": "af48a3c",
          "subject": "Add document context menus"
        },
        {
          "hash": "251ffd524eb57fe92e5122a6c967a64e38a07b01",
          "shortHash": "251ffd5",
          "subject": "Open vault documents from agent links"
        }
      ]
    },
    {
      "version": "0.12.3",
      "date": "2026-06-26T17:11:24+02:00",
      "commits": [
        {
          "hash": "81732499890862d7920428c9d0fe4d01abeed621",
          "shortHash": "8173249",
          "subject": "Prepare release 0.12.3"
        },
        {
          "hash": "5adce73158535b5f564b3958b14601896baad825",
          "shortHash": "5adce73",
          "subject": "Make tab row opaque"
        },
        {
          "hash": "37911a0df7d87f020fcd283ba6bf8aeb49363998",
          "shortHash": "37911a0",
          "subject": "Add empty document picker"
        },
        {
          "hash": "85341370f038f6d1a764607cb5647884b8a55e5c",
          "shortHash": "8534137",
          "subject": "Add document tabs"
        },
        {
          "hash": "927c7c0d1cf7bbf2f7b0663d4c9a0b0dc4328e42",
          "shortHash": "927c7c0",
          "subject": "Fix Windows update restart"
        }
      ]
    },
    {
      "version": "0.12.2",
      "date": "2026-06-26T15:23:09+02:00",
      "commits": [
        {
          "hash": "69787b427ef9e1ee771ff1167f5cd8b3430de921",
          "shortHash": "69787b4",
          "subject": "Prepare release 0.12.2"
        },
        {
          "hash": "ba8e6bd466ac660a28cea4ad3ff15915689a77b7",
          "shortHash": "ba8e6bd",
          "subject": "Fix Windows titlebar header layout"
        }
      ]
    },
    {
      "version": "0.12.1",
      "date": "2026-06-26T12:37:09+02:00",
      "commits": [
        {
          "hash": "691c1ea04c0fb8e678c5392a195e97baf5880c91",
          "shortHash": "691c1ea",
          "subject": "Prepare release 0.12.1"
        },
        {
          "hash": "335fda4e657e072e5cb83e7b28ce150f117887cb",
          "shortHash": "335fda4",
          "subject": "Update expected skill versions in workspace e2e test"
        }
      ]
    },
    {
      "version": "0.12.0",
      "date": "2026-06-26T12:19:14+02:00",
      "commits": [
        {
          "hash": "58299b806e07cd874eef5e93d992e9337280215a",
          "shortHash": "58299b8",
          "subject": "Prepare release 0.12.0"
        },
        {
          "hash": "f69091fd24be22669afe803a162130785897ae63",
          "shortHash": "f69091f",
          "subject": "Support Markdown vaults"
        },
        {
          "hash": "fb41e92fd594321a13bc40caf2012eccebda4f81",
          "shortHash": "fb41e92",
          "subject": "Expose vault setup from settings"
        },
        {
          "hash": "9674487da8964849a076f08106e995a9068c0d87",
          "shortHash": "9674487",
          "subject": "Fetch full history for CI builds"
        },
        {
          "hash": "fdcb5dffccaa7e8a55d2bdc0b7a6d96abcfdf6c1",
          "shortHash": "fdcb5df",
          "subject": "Refresh generated changelog"
        },
        {
          "hash": "0e0be8c1cd64a7632f417b3c75e4066649cb88ce",
          "shortHash": "0e0be8c",
          "subject": "Add vault metadata init flow"
        },
        {
          "hash": "ccccbdaccbddd3892df7a7290ec3d6468a487cab",
          "shortHash": "ccccbda",
          "subject": "Show agent skill update details"
        }
      ]
    },
    {
      "version": "0.11.1",
      "date": "2026-06-25T10:23:10+02:00",
      "commits": [
        {
          "hash": "98ae62a7eb490b122f55f88088ca58e7f854e9b5",
          "shortHash": "98ae62a",
          "subject": "Prepare release 0.11.1"
        },
        {
          "hash": "0057b76d00fdf2b43d281022872d32ff1509ccbb",
          "shortHash": "0057b76",
          "subject": "Quote skill description to emit valid YAML frontmatter"
        }
      ]
    },
    {
      "version": "0.11.0",
      "date": "2026-06-24T20:44:35+02:00",
      "commits": [
        {
          "hash": "29c3dfbb3c4d2272e22ebe738f74c69551bb3d4d",
          "shortHash": "29c3dfb",
          "subject": "Prepare release 0.11.0"
        },
        {
          "hash": "9a65038831647ace1d9be754bb6c806e5fabef1e",
          "shortHash": "9a65038",
          "subject": "Allow GitHub avatars in renderer CSP"
        },
        {
          "hash": "a82fc7a376b29bbbe699ea20812001344b42c075",
          "shortHash": "a82fc7a",
          "subject": "Fix GitHub connect dialog overflow"
        },
        {
          "hash": "9c9b64c12fe8c4a1dc483671985ab5c0b78c6c64",
          "shortHash": "9c9b64c",
          "subject": "Add settings reset and remove-vault actions"
        },
        {
          "hash": "8955aa53e34c469012a06f4a71e64eb73053e268",
          "shortHash": "8955aa5",
          "subject": "Configure GitHub OAuth client id for builds"
        },
        {
          "hash": "fe263be17548619dee58436f79db8c9d60197668",
          "shortHash": "fe263be",
          "subject": "Fix onboarding E2E test for Advanced section"
        },
        {
          "hash": "54dcd4473d990539c3b1e0e0f309bb1c18821a39",
          "shortHash": "54dcd44",
          "subject": "Add one-click GitHub sign-in with multiple accounts"
        }
      ]
    },
    {
      "version": "0.10.9",
      "date": "2026-06-23T16:27:06+02:00",
      "commits": [
        {
          "hash": "2f56426bc161ebb6358b618344aa37bd53a61fcd",
          "shortHash": "2f56426",
          "subject": "Prepare release 0.10.9"
        },
        {
          "hash": "a22d34a5e37e748513db535ec94e841c20da9933",
          "shortHash": "a22d34a",
          "subject": "Center the Windows app icon"
        },
        {
          "hash": "98dfaf98efaee3e874f4390e432d1cc1c0e6d86e",
          "shortHash": "98dfaf9",
          "subject": "Add document PDF export"
        }
      ]
    },
    {
      "version": "0.10.8",
      "date": "2026-06-23T15:20:21+02:00",
      "commits": [
        {
          "hash": "2360b00f6447d6e1a1696a6ca74739269861caf8",
          "shortHash": "2360b00",
          "subject": "Prepare release 0.10.8"
        },
        {
          "hash": "80e277ba732af78bf015b4a2bf896063987efa28",
          "shortHash": "80e277b",
          "subject": "Enforce commit quality checks"
        },
        {
          "hash": "7c832298bff21a2628ca9b5f8f0a4d9bd2ec24ea",
          "shortHash": "7c83229",
          "subject": "Add larger Windows app icon"
        },
        {
          "hash": "d9ea57a247bb66895f018d3e2d9a475e505c32ec",
          "shortHash": "d9ea57a",
          "subject": "Auto-refresh vault document changes"
        }
      ]
    },
    {
      "version": "0.10.7",
      "date": "2026-06-23T11:14:50+02:00",
      "commits": [
        {
          "hash": "e5eeae07bd2a50251d6a86c703619c8aa5bd80ce",
          "shortHash": "e5eeae0",
          "subject": "Fix transparent app icon background"
        }
      ]
    },
    {
      "version": "0.10.6",
      "date": "2026-06-23T11:01:10+02:00",
      "commits": [
        {
          "hash": "cc7b942d2ae34c4407969276e7a3bbf7cf3d3d02",
          "shortHash": "cc7b942",
          "subject": "Prepare release 0.10.6"
        },
        {
          "hash": "90494a20974b74028c2ad337db534c41033742da",
          "shortHash": "90494a2",
          "subject": "Add lint and format checks to CI"
        }
      ]
    },
    {
      "version": "0.10.5",
      "date": "2026-06-23T10:47:09+02:00",
      "commits": [
        {
          "hash": "a5b8deef7e8e58924c55420fa89f24145742a95c",
          "shortHash": "a5b8dee",
          "subject": "Fix changelog release notes rendering"
        }
      ]
    },
    {
      "version": "0.10.4",
      "date": "2026-06-23T10:27:25+02:00",
      "commits": [
        {
          "hash": "5b362a9621981f8cf8e15c771dd3678fcb0f107c",
          "shortHash": "5b362a9",
          "subject": "Prepare release 0.10.4"
        },
        {
          "hash": "7e3cf94032525103ebbbc78c306c9afe4980b6a7",
          "shortHash": "7e3cf94",
          "subject": "Remove personal name from skill descriptions"
        }
      ]
    },
    {
      "version": "0.10.3",
      "date": "2026-06-23T10:06:45+02:00",
      "commits": [
        {
          "hash": "5aa8be0a991c7aea8463df660d1b79278c1eed0d",
          "shortHash": "5aa8be0",
          "subject": "Add app changelog and security prompt"
        }
      ]
    },
    {
      "version": "0.10.2",
      "date": "2026-06-23T09:45:48+02:00",
      "commits": [
        {
          "hash": "08988d8fe1335256903758e3032f8bb10315aa60",
          "shortHash": "08988d8",
          "subject": "Improve Git credential errors"
        }
      ]
    },
    {
      "version": "0.10.1",
      "date": "2026-06-23T09:08:11+02:00",
      "commits": [
        {
          "hash": "5b1d5f6bbfcadeb6fe509caa2c0231af7e917eca",
          "shortHash": "5b1d5f6",
          "subject": "Prepare release 0.10.1"
        }
      ]
    },
    {
      "version": "0.10.0",
      "date": "2026-06-22T13:39:58+02:00",
      "commits": [
        {
          "hash": "a9e4f1769e4c025f869c15b12e3d0bb59b581165",
          "shortHash": "a9e4f17",
          "subject": "build: prepare version 0.10.0"
        },
        {
          "hash": "943f5a413e6bd2bf56118243feb0dcaa93bed199",
          "shortHash": "943f5a4",
          "subject": "Style scrollbars for light and dark themes"
        },
        {
          "hash": "99b487a4e848453dee9a8fbca0a1a528047df7c1",
          "shortHash": "99b487a",
          "subject": "feat: add document line history"
        }
      ]
    },
    {
      "version": "0.9.0",
      "date": "2026-06-22T11:15:59+02:00",
      "commits": [
        {
          "hash": "903fdbfb5992e1838826a811db258e54000838fc",
          "shortHash": "903fdbf",
          "subject": "build: prepare version 0.9.0"
        },
        {
          "hash": "07818e29b54e63d8b98a22b1d613b62e5bb8048e",
          "shortHash": "07818e2",
          "subject": "test: consolidate end-to-end flows"
        },
        {
          "hash": "875c484fcafa912ff181e971465526375651facc",
          "shortHash": "875c484",
          "subject": "feat: integrate Windows window controls"
        },
        {
          "hash": "e839006535f682b6d69f0567292c22109688131e",
          "shortHash": "e839006",
          "subject": "fix: compact agent skills status"
        }
      ]
    },
    {
      "version": "0.8.1",
      "date": "2026-06-22T10:15:20+02:00",
      "commits": [
        {
          "hash": "337d58392db217d9afe83ac5e4326ea0a6c3540d",
          "shortHash": "337d583",
          "subject": "build: prepare version 0.8.1"
        },
        {
          "hash": "20f564e1c543de767ab9e0dc0360fbdf3aae32a8",
          "shortHash": "20f564e",
          "subject": "fix: isolate skill install dir under test so e2e never touches real skills"
        },
        {
          "hash": "123410270c83a117684285c1ee4413798dd17e11",
          "shortHash": "1234102",
          "subject": "fix: re-read vault.json on list so structure edits surface"
        }
      ]
    },
    {
      "version": "0.8.0",
      "date": "2026-06-22T08:30:23+02:00",
      "commits": [
        {
          "hash": "7448c5d2e957059b10d811f2d959929300ff649d",
          "shortHash": "7448c5d",
          "subject": "build: prepare version 0.8.0"
        },
        {
          "hash": "cc9bd7b1e17c241d1ed92461cfc3b53340c5f1d8",
          "shortHash": "cc9bd7b",
          "subject": "Move update and skills tools to sidebar, add tour"
        },
        {
          "hash": "9cfbe7205a89aa425529d2d86a6bfd658540ad23",
          "shortHash": "9cfbe72",
          "subject": "feat: refocus reviewer skill and expand vault-guide linking rules"
        },
        {
          "hash": "bda7d2304e6acc6e0d97d8a42e8d72d46f6895b0",
          "shortHash": "bda7d23",
          "subject": "feat: add auto-installed document reviewer agent skill"
        },
        {
          "hash": "1cc03289aec93eaceb6edc3cb88dbd260602bd06",
          "shortHash": "1cc0328",
          "subject": "docs: propose auto-installed document reviewer agent"
        }
      ]
    },
    {
      "version": "0.7.0",
      "date": "2026-06-21T18:15:59+02:00",
      "commits": [
        {
          "hash": "96275e9646bf273cc1f14dd81d3fcc95d95a287a",
          "shortHash": "96275e9",
          "subject": "build: prepare version 0.7.0"
        },
        {
          "hash": "582d59c6dc8dd35c80c6361402bd2266a4650fec",
          "shortHash": "582d59c",
          "subject": "feat: edit desired vault structure from settings"
        }
      ]
    },
    {
      "version": "0.6.0",
      "date": "2026-06-21T17:15:36+02:00",
      "commits": [
        {
          "hash": "79825b617da5681c236d432e626f517f488170ab",
          "shortHash": "79825b6",
          "subject": "build: prepare version 0.6.0"
        },
        {
          "hash": "b42c2c6be78038a65c1efe90b020c93a9ecaf393",
          "shortHash": "b42c2c6",
          "subject": "test: add e2e coverage for vault settings dialog"
        },
        {
          "hash": "4298bdc141937bb5325d032ba23ba0731616c2aa",
          "shortHash": "4298bdc",
          "subject": "refactor: drop redundant type field from vault structure"
        },
        {
          "hash": "fdb883599e01867678fc5c028f2c675754d154eb",
          "shortHash": "fdb8835",
          "subject": "feat: add vault structure metadata and default language"
        }
      ]
    },
    {
      "version": "0.5.0",
      "date": "2026-06-21T11:27:42+02:00",
      "commits": [
        {
          "hash": "a735799777e3299280759a3ed051e890025d866c",
          "shortHash": "a735799",
          "subject": "build: prepare version 0.5.0"
        },
        {
          "hash": "6e36a2c652c1166e8c262722ea8f3c58ccb967e0",
          "shortHash": "6e36a2c",
          "subject": "feat: modernize macOS title bar and app icon"
        }
      ]
    },
    {
      "version": "0.4.1",
      "date": "2026-06-21T11:08:43+02:00",
      "commits": [
        {
          "hash": "45ed237454b0e283d909953eef8d5c6f1043dec7",
          "shortHash": "45ed237",
          "subject": "build: prepare version 0.4.1"
        },
        {
          "hash": "215d3e5dd18621b7ffaff5aeb52b4e0a11eb05ac",
          "shortHash": "215d3e5",
          "subject": "fix: avoid spaces in release artifact names"
        }
      ]
    },
    {
      "version": "0.4.0",
      "date": "2026-06-21T10:35:19+02:00",
      "commits": [
        {
          "hash": "dfd29c52e3cf1108ee1d5fc4f0b501b4cd6bb184",
          "shortHash": "dfd29c5",
          "subject": "build: prepare version 0.4.0"
        },
        {
          "hash": "9aecc44db71245c5c22f1902dbef6c3b6aab220f",
          "shortHash": "9aecc44",
          "subject": "feat: add skill installer and vault management"
        }
      ]
    },
    {
      "version": "0.3.0",
      "date": "2026-06-21T09:57:11+02:00",
      "commits": [
        {
          "hash": "89fa13acdff47110c1a2c5353a10409cf914fb36",
          "shortHash": "89fa13a",
          "subject": "build: prepare version 0.3.0"
        },
        {
          "hash": "1afa03ac6e63d94c7e905bff6feeb96e5ebd8bee",
          "shortHash": "1afa03a",
          "subject": "test: attach named screenshots to e2e report"
        },
        {
          "hash": "7ab7deac715fd53a4957a0e7640d1ddcce9ce609",
          "shortHash": "7ab7dea",
          "subject": "test: add Playwright end-to-end test suite"
        },
        {
          "hash": "a93b46e41acd39895782bbfd8cf90da05e73d734",
          "shortHash": "a93b46e",
          "subject": "feat: show app version and update prompt in toolbar"
        }
      ]
    },
    {
      "version": "0.2.2",
      "date": "2026-06-19T16:02:34+02:00",
      "commits": [
        {
          "hash": "9734282df5bb8ec9b59a0d815575b19b4f6cca8c",
          "shortHash": "9734282",
          "subject": "build: prepare version 0.2.2"
        },
        {
          "hash": "9c87b36be1616c6be387740b88c7cc2924a1110c",
          "shortHash": "9c87b36",
          "subject": "feat: apply Data Vault branding"
        }
      ]
    },
    {
      "version": "0.2.1",
      "date": "2026-06-19T15:49:22+02:00",
      "commits": [
        {
          "hash": "b6fc83de1a24979a5e4a05b7f27def87604372a7",
          "shortHash": "b6fc83d",
          "subject": "build: prepare signed macOS release"
        }
      ]
    },
    {
      "version": "0.2.0",
      "date": "2026-06-19T15:08:21+02:00",
      "commits": [
        {
          "hash": "9df0ed49ddd39ebb088f363c0376c2677275fb95",
          "shortHash": "9df0ed4",
          "subject": "feat: add application update workflow"
        }
      ]
    },
    {
      "version": "0.1.0",
      "date": "2026-06-19T14:43:56+02:00",
      "commits": [
        {
          "hash": "a069ddbb0ecb1355aef57d54c43801300c9211b9",
          "shortHash": "a069ddb",
          "subject": "feat: add per-vault quick notes panel"
        },
        {
          "hash": "70408e98a53c8a2fa44eef1b6b5af6d607a29778",
          "shortHash": "70408e9",
          "subject": "fix: repair Linux release packaging"
        },
        {
          "hash": "cc55121bf0351782c7a4dd9a844f120cf40fb91e",
          "shortHash": "cc55121",
          "subject": "feat: add Git-backed vault desktop app"
        }
      ]
    }
  ]
} satisfies AppChangelog;
