// Generated by scripts/generate-changelog.mjs. Do not edit by hand.
import type { AppChangelog } from "../src/types";

export const APP_CHANGELOG = {
  "generatedAt": "2026-06-23T10:24:12+02:00",
  "repositoryUrl": "https://github.com/BasPeter/data-vault.git",
  "releases": [
    {
      "version": "0.10.4",
      "date": "2026-06-23T10:24:12+02:00",
      "commits": [
        {
          "hash": "7e3cf94032525103ebbbc78c306c9afe4980b6a7",
          "shortHash": "7e3cf94",
          "subject": "Remove personal name from skill descriptions"
        }
      ]
    },
    {
      "version": "0.10.3",
      "date": "2026-06-23T10:06:45+02:00",
      "commits": [
        {
          "hash": "5aa8be0a991c7aea8463df660d1b79278c1eed0d",
          "shortHash": "5aa8be0",
          "subject": "Add app changelog and security prompt"
        }
      ]
    },
    {
      "version": "0.10.2",
      "date": "2026-06-23T09:45:48+02:00",
      "commits": [
        {
          "hash": "08988d8fe1335256903758e3032f8bb10315aa60",
          "shortHash": "08988d8",
          "subject": "Improve Git credential errors"
        }
      ]
    },
    {
      "version": "0.10.1",
      "date": "2026-06-23T09:08:11+02:00",
      "commits": [
        {
          "hash": "5b1d5f6bbfcadeb6fe509caa2c0231af7e917eca",
          "shortHash": "5b1d5f6",
          "subject": "Prepare release 0.10.1"
        }
      ]
    },
    {
      "version": "0.10.0",
      "date": "2026-06-22T13:39:58+02:00",
      "commits": [
        {
          "hash": "a9e4f1769e4c025f869c15b12e3d0bb59b581165",
          "shortHash": "a9e4f17",
          "subject": "build: prepare version 0.10.0"
        },
        {
          "hash": "943f5a413e6bd2bf56118243feb0dcaa93bed199",
          "shortHash": "943f5a4",
          "subject": "Style scrollbars for light and dark themes"
        },
        {
          "hash": "99b487a4e848453dee9a8fbca0a1a528047df7c1",
          "shortHash": "99b487a",
          "subject": "feat: add document line history"
        }
      ]
    },
    {
      "version": "0.9.0",
      "date": "2026-06-22T11:15:59+02:00",
      "commits": [
        {
          "hash": "903fdbfb5992e1838826a811db258e54000838fc",
          "shortHash": "903fdbf",
          "subject": "build: prepare version 0.9.0"
        },
        {
          "hash": "07818e29b54e63d8b98a22b1d613b62e5bb8048e",
          "shortHash": "07818e2",
          "subject": "test: consolidate end-to-end flows"
        },
        {
          "hash": "875c484fcafa912ff181e971465526375651facc",
          "shortHash": "875c484",
          "subject": "feat: integrate Windows window controls"
        },
        {
          "hash": "e839006535f682b6d69f0567292c22109688131e",
          "shortHash": "e839006",
          "subject": "fix: compact agent skills status"
        }
      ]
    },
    {
      "version": "0.8.1",
      "date": "2026-06-22T10:15:20+02:00",
      "commits": [
        {
          "hash": "337d58392db217d9afe83ac5e4326ea0a6c3540d",
          "shortHash": "337d583",
          "subject": "build: prepare version 0.8.1"
        },
        {
          "hash": "20f564e1c543de767ab9e0dc0360fbdf3aae32a8",
          "shortHash": "20f564e",
          "subject": "fix: isolate skill install dir under test so e2e never touches real skills"
        },
        {
          "hash": "123410270c83a117684285c1ee4413798dd17e11",
          "shortHash": "1234102",
          "subject": "fix: re-read vault.json on list so structure edits surface"
        }
      ]
    },
    {
      "version": "0.8.0",
      "date": "2026-06-22T08:30:23+02:00",
      "commits": [
        {
          "hash": "7448c5d2e957059b10d811f2d959929300ff649d",
          "shortHash": "7448c5d",
          "subject": "build: prepare version 0.8.0"
        },
        {
          "hash": "cc9bd7b1e17c241d1ed92461cfc3b53340c5f1d8",
          "shortHash": "cc9bd7b",
          "subject": "Move update and skills tools to sidebar, add tour"
        },
        {
          "hash": "9cfbe7205a89aa425529d2d86a6bfd658540ad23",
          "shortHash": "9cfbe72",
          "subject": "feat: refocus reviewer skill and expand vault-guide linking rules"
        },
        {
          "hash": "bda7d2304e6acc6e0d97d8a42e8d72d46f6895b0",
          "shortHash": "bda7d23",
          "subject": "feat: add auto-installed document reviewer agent skill"
        },
        {
          "hash": "1cc03289aec93eaceb6edc3cb88dbd260602bd06",
          "shortHash": "1cc0328",
          "subject": "docs: propose auto-installed document reviewer agent"
        }
      ]
    },
    {
      "version": "0.7.0",
      "date": "2026-06-21T18:15:59+02:00",
      "commits": [
        {
          "hash": "96275e9646bf273cc1f14dd81d3fcc95d95a287a",
          "shortHash": "96275e9",
          "subject": "build: prepare version 0.7.0"
        },
        {
          "hash": "582d59c6dc8dd35c80c6361402bd2266a4650fec",
          "shortHash": "582d59c",
          "subject": "feat: edit desired vault structure from settings"
        }
      ]
    },
    {
      "version": "0.6.0",
      "date": "2026-06-21T17:15:36+02:00",
      "commits": [
        {
          "hash": "79825b617da5681c236d432e626f517f488170ab",
          "shortHash": "79825b6",
          "subject": "build: prepare version 0.6.0"
        },
        {
          "hash": "b42c2c6be78038a65c1efe90b020c93a9ecaf393",
          "shortHash": "b42c2c6",
          "subject": "test: add e2e coverage for vault settings dialog"
        },
        {
          "hash": "4298bdc141937bb5325d032ba23ba0731616c2aa",
          "shortHash": "4298bdc",
          "subject": "refactor: drop redundant type field from vault structure"
        },
        {
          "hash": "fdb883599e01867678fc5c028f2c675754d154eb",
          "shortHash": "fdb8835",
          "subject": "feat: add vault structure metadata and default language"
        }
      ]
    },
    {
      "version": "0.5.0",
      "date": "2026-06-21T11:27:42+02:00",
      "commits": [
        {
          "hash": "a735799777e3299280759a3ed051e890025d866c",
          "shortHash": "a735799",
          "subject": "build: prepare version 0.5.0"
        },
        {
          "hash": "6e36a2c652c1166e8c262722ea8f3c58ccb967e0",
          "shortHash": "6e36a2c",
          "subject": "feat: modernize macOS title bar and app icon"
        }
      ]
    },
    {
      "version": "0.4.1",
      "date": "2026-06-21T11:08:43+02:00",
      "commits": [
        {
          "hash": "45ed237454b0e283d909953eef8d5c6f1043dec7",
          "shortHash": "45ed237",
          "subject": "build: prepare version 0.4.1"
        },
        {
          "hash": "215d3e5dd18621b7ffaff5aeb52b4e0a11eb05ac",
          "shortHash": "215d3e5",
          "subject": "fix: avoid spaces in release artifact names"
        }
      ]
    },
    {
      "version": "0.4.0",
      "date": "2026-06-21T10:35:19+02:00",
      "commits": [
        {
          "hash": "dfd29c52e3cf1108ee1d5fc4f0b501b4cd6bb184",
          "shortHash": "dfd29c5",
          "subject": "build: prepare version 0.4.0"
        },
        {
          "hash": "9aecc44db71245c5c22f1902dbef6c3b6aab220f",
          "shortHash": "9aecc44",
          "subject": "feat: add skill installer and vault management"
        }
      ]
    },
    {
      "version": "0.3.0",
      "date": "2026-06-21T09:57:11+02:00",
      "commits": [
        {
          "hash": "89fa13acdff47110c1a2c5353a10409cf914fb36",
          "shortHash": "89fa13a",
          "subject": "build: prepare version 0.3.0"
        },
        {
          "hash": "1afa03ac6e63d94c7e905bff6feeb96e5ebd8bee",
          "shortHash": "1afa03a",
          "subject": "test: attach named screenshots to e2e report"
        },
        {
          "hash": "7ab7deac715fd53a4957a0e7640d1ddcce9ce609",
          "shortHash": "7ab7dea",
          "subject": "test: add Playwright end-to-end test suite"
        },
        {
          "hash": "a93b46e41acd39895782bbfd8cf90da05e73d734",
          "shortHash": "a93b46e",
          "subject": "feat: show app version and update prompt in toolbar"
        }
      ]
    },
    {
      "version": "0.2.2",
      "date": "2026-06-19T16:02:34+02:00",
      "commits": [
        {
          "hash": "9734282df5bb8ec9b59a0d815575b19b4f6cca8c",
          "shortHash": "9734282",
          "subject": "build: prepare version 0.2.2"
        },
        {
          "hash": "9c87b36be1616c6be387740b88c7cc2924a1110c",
          "shortHash": "9c87b36",
          "subject": "feat: apply Data Vault branding"
        }
      ]
    },
    {
      "version": "0.2.1",
      "date": "2026-06-19T15:49:22+02:00",
      "commits": [
        {
          "hash": "b6fc83de1a24979a5e4a05b7f27def87604372a7",
          "shortHash": "b6fc83d",
          "subject": "build: prepare signed macOS release"
        }
      ]
    },
    {
      "version": "0.2.0",
      "date": "2026-06-19T15:08:21+02:00",
      "commits": [
        {
          "hash": "9df0ed49ddd39ebb088f363c0376c2677275fb95",
          "shortHash": "9df0ed4",
          "subject": "feat: add application update workflow"
        }
      ]
    },
    {
      "version": "0.1.0",
      "date": "2026-06-19T14:43:56+02:00",
      "commits": [
        {
          "hash": "a069ddbb0ecb1355aef57d54c43801300c9211b9",
          "shortHash": "a069ddb",
          "subject": "feat: add per-vault quick notes panel"
        },
        {
          "hash": "70408e98a53c8a2fa44eef1b6b5af6d607a29778",
          "shortHash": "70408e9",
          "subject": "fix: repair Linux release packaging"
        },
        {
          "hash": "cc55121bf0351782c7a4dd9a844f120cf40fb91e",
          "shortHash": "cc55121",
          "subject": "feat: add Git-backed vault desktop app"
        }
      ]
    }
  ]
} satisfies AppChangelog;
