import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { createHash } from "node:crypto";
import { randomUUID } from "node:crypto";
import type { SkillStatus, VaultSummary } from "../src/types";

// Bump when the SKILL.md template or its guidance changes so that installed
// copies are reported as outdated and the user is prompted to re-install.
const SKILL_VERSION = "1";
const SKILL_NAME = "vault-guide";
const SKILL_FILE = "SKILL.md";
const MARKER_FILE = ".vault-guide.json";

type Marker = { version: string; fingerprint: string };

function atomicWrite(file: string, content: string, mode: number): void {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  const temporary = path.join(path.dirname(file), `.${path.basename(file)}-${randomUUID()}.tmp`);
  try {
    fs.writeFileSync(temporary, content, { encoding: "utf8", mode });
    fs.renameSync(temporary, file);
  } finally {
    fs.rmSync(temporary, { force: true });
  }
}

function readJson<T>(file: string): T | null {
  try {
    return JSON.parse(fs.readFileSync(file, "utf8")) as T;
  } catch {
    return null;
  }
}

function vaultEntry(vault: VaultSummary): string {
  const lines = [
    `### ${vault.name}`,
    "",
    `- Repository path: \`${vault.repositoryPath}\``,
    `- Documents directory: \`${vault.repositoryPath}/documents\` (unless \`vault.json\` sets \`documentsDirectory\`)`,
  ];
  if (vault.remoteUrl) lines.push(`- Git remote: \`${vault.remoteUrl}\``);
  return lines.join("\n");
}

export class SkillService {
  private readonly targets: string[];

  constructor(homeDirectory: string = os.homedir()) {
    this.targets = [
      path.join(homeDirectory, ".claude", "skills", SKILL_NAME),
      path.join(homeDirectory, ".codex", "skills", SKILL_NAME),
    ];
  }

  render(vaults: VaultSummary[]): string {
    const description =
      "Read, create, and edit documents across Bas Peter Dijkema's local Data Vault " +
      "knowledge repositories. Use when asked to look something up in a vault, take " +
      "notes, or update vault documents.";
    const vaultSection = vaults.length
      ? vaults.map(vaultEntry).join("\n\n")
      : "_No vaults are registered yet. Open the Data Vault app and add a vault, then re-install this skill._";

    return `---
name: ${SKILL_NAME}
description: ${description}
---

# Vault Guide

Data Vault repositories are Git-backed collections of content-only HTML
documents. This skill lists the user's registered vaults and explains how to
read and edit their documents directly on disk.

<!-- Generated by the Data Vault app (skill version ${SKILL_VERSION}). Do not edit by hand; re-install from the app to refresh. -->

## Vault format

- A vault is a local Git repository. Documents live under \`documents/\` unless
  \`vault.json\` sets a different \`documentsDirectory\`.
- Each document is a content-only \`.html\` fragment (no \`<html>\`/\`<body>\`
  wrapper). An optional leading \`<!--vault ... -->\` block carries metadata:

  \`\`\`html
  <!--vault
  title: Example title
  date: 2026-06-21
  tags: one, two
  -->
  <h1>Example</h1>
  <p>Body with an <a href="#folder/other.html">internal link</a>.</p>
  \`\`\`

- Internal links are hashes whose value is another document's ID (its path
  relative to the documents directory, e.g. \`#10-knowledge/overview.html\`).
- Mermaid diagrams are stored as \`<pre class="mermaid">...</pre>\` blocks.
- \`quick-notes.html\` at the documents root is a reserved local scratchpad; do
  not treat it as a regular document.

## Available vaults

${vaultSection}

## Working with documents

- **Read**: open \`.html\` files under the vault's documents directory.
- **Create / edit**: write content-only HTML fragments. Add a \`<!--vault -->\`
  block for title/date/tags, use \`#<document-id>\` hash links for cross-links,
  and keep Mermaid source inside \`<pre class="mermaid">\` blocks.
- **Commit**: each vault is its own Git repository — commit and push changes in
  that repository. Never write vault content into the Data Vault application
  repository itself.
`;
  }

  fingerprint(vaults: VaultSummary[]): string {
    const payload = JSON.stringify({
      version: SKILL_VERSION,
      vaults: vaults.map((vault) => ({
        name: vault.name,
        repositoryPath: vault.repositoryPath,
        remoteUrl: vault.remoteUrl ?? null,
      })),
    });
    return createHash("sha256").update(payload).digest("hex");
  }

  install(vaults: VaultSummary[]): SkillStatus {
    const skill = this.render(vaults);
    const marker: Marker = { version: SKILL_VERSION, fingerprint: this.fingerprint(vaults) };
    for (const target of this.targets) {
      atomicWrite(path.join(target, SKILL_FILE), skill, 0o644);
      atomicWrite(path.join(target, MARKER_FILE), `${JSON.stringify(marker, null, 2)}\n`, 0o600);
    }
    return this.status(vaults);
  }

  status(vaults: VaultSummary[]): SkillStatus {
    const current = this.fingerprint(vaults);
    let installed = true;
    let matches = true;
    for (const target of this.targets) {
      if (!fs.existsSync(path.join(target, SKILL_FILE))) {
        installed = false;
        continue;
      }
      const marker = readJson<Marker>(path.join(target, MARKER_FILE));
      if (!marker || marker.fingerprint !== current) matches = false;
    }
    const state: SkillStatus["state"] = !installed ? "not-installed" : matches ? "current" : "outdated";
    return { state, version: SKILL_VERSION, vaultCount: vaults.length };
  }
}
